### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/funcionario/10 HTTP/1.1

### Verbo POST – adicionar
POST http://localhost:8000/funcionario/ HTTP/1.1
content-type: application/json

{
    "nome": "Osmar",
    "matricula": "2165465432",
    "cpf": "1234567900",
    "telefone": "45421265254",
    "grupo": 4,
    "senha": "123456"
}

### Verbo PUT – atualiza
PUT http://localhost:8000/funcionario/1 HTTP/1.1
content-type: application/json

{
    "nome": "Osmar Steffen",
    "matricula": "2165465432",
    "cpf": "1234567902",
    "telefone": "49999999999",
    "grupo": 1,
    "senha": "nova_senha_123"
}

### Verbo DELETE - excluir
DELETE http://localhost:8000/funcionario/1 HTTP/1.1


#Osmar Steffen